AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless

  Sample SAM Template for serverless
  
Globals:
  Function:
    Timeout: 3

Resources:
  BuildDocsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build-docs/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        BuildDocs:
          Type: Api
          Properties:
            Path: /build-docs
            Method: get

Outputs:
  BuildDocsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/build-docs/"
  BuildDocsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt BuildDocsFunction.Arn
  BuildDocsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt BuildDocsFunctionRole.Arn
