version: '3.7'

services:
  wordpress:
    container_name: lab_web
    image: gpalab/wordpress:latest
    depends_on:
      - db
    environment:
      - 'DB_PORT=3306'
    expose:
      - '80'
    volumes:
      - ../plugins:/www/local/sites-enabled/lab_dev/wp-content/plugins
      - ../themes:/www/local/sites-enabled/lab_dev/wp-content/themes
      - ./config/lab.conf:/etc/httpd/conf.d/lab.conf
      - ~/.ssh:/root/.ssh:ro

  db:
    container_name: lab_db
    image: gpalab/mariadb
    expose:
      - '3306'
    volumes:
      - mariadb:/var/lib/mysql
      - mariaconf:/etc/mysql

  adminer:
    container_name: lab_adminer
    image: gpalab/adminer
    environment:
      ADMINER_DEFAULT_SERVER: lab_db
    expose:
      - '8080'

networks:
  default:
    name: lab_net

volumes:
  mariadb:
    driver: local
    name: lab_db
  mariaconf:
    driver: local
    name: lab_db_conf
