version: '3.7'

services:
  caddy:
    container_name: lab_caddy
    image: 'caddy:latest'
    networks:
      - lab-net
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/caddy-config:/config
      - ./config/caddy-data:/data
      - ./config/Caddyfile:/etc/caddy/Caddyfile

networks:
  lab-net:
    external: true
    name: lab_net
