remote_theme: IIP-Design/lab-notes

title: GPA/Lab Headless
author: Bureau of Global Public Affairs (GPA) Digital Lab Team
author_homepage: https://github.com/IIP-Design
repository: IIP-Design/lab-headless
description: A WordPress headless CMS monorepo.
favicon: /lab-headless/assets/img/favicon.ico
logo: /lab-headless/assets/img/dos_seal.svg
show_downloads: false
show_nav: false

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
